"""Run four E2E ingestions with complete audit trail.

Each scenario saves to audit_dir/{scenario}/:
  result.json, source-envelope.json, evidence-manifest.json,
  command-log.txt, candidate.md
"""
from __future__ import annotations

import json, hashlib, os, subprocess, sys, time, uuid, urllib.request
from datetime import datetime, timezone
from pathlib import Path

_REPO = Path(r"D:\XiangMuLuoDi\Clone\1263-ux\claude-code-knowledge-studios")
_AUDIT = Path(os.environ["TEMP"]) / "oks-audit-dc15e73"

def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def ensure_dir(p: Path) -> Path:
    p.mkdir(parents=True, exist_ok=True)
    return p

def run_scenario(label: str, run_prefix: str, source_uri: str, modality: str,
                 access: str, providers: list[str], build_fn) -> dict:
    """Execute one scenario end-to-end and save audit trail."""
    scenario_dir = ensure_dir(_AUDIT / "e2e" / label)
    log_path = scenario_dir / "command-log.txt"
    log_lines = []

    def log(msg: str):
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        line = f"[{ts}] {msg}"
        print(line)
        log_lines.append(line)

    run_id = f"run-{run_prefix}-{uuid.uuid4().hex[:8]}"
    source_id = f"{label}-{uuid.uuid4().hex[:8]}"
    log(f"START run_id={run_id} source_id={source_id}")
    log(f"source_uri={source_uri} modality={modality} access={access}")
    log(f"providers={providers}")

    # Let the build_fn construct artifacts, evidence, manifest
    t0 = time.time()
    result = build_fn(run_id, source_id, source_uri, log)
    elapsed_ms = int((time.time() - t0) * 1000)
    log(f"Build completed in {elapsed_ms}ms")

    man_dir = _REPO / ".oks" / "runs" / run_id / "manifest"

    # Save source-envelope and manifest to audit
    se_src = man_dir / "source-envelope.json"
    em_src = man_dir / "evidence-manifest.json"
    if se_src.exists():
        (scenario_dir / "source-envelope.json").write_text(se_src.read_text(encoding="utf-8"), encoding="utf-8")
    if em_src.exists():
        (scenario_dir / "evidence-manifest.json").write_text(em_src.read_text(encoding="utf-8"), encoding="utf-8")

    # oks raw-commit
    log(f"RUNNING: oks raw-commit {man_dir} --overwrite")
    rc = subprocess.run(["oks", "raw-commit", str(man_dir), "--overwrite"],
                       capture_output=True, text=True)
    log(f"raw-commit exit={rc.returncode}")
    log(f"raw-commit stdout: {rc.stdout[:500]}")
    if rc.stderr:
        log(f"raw-commit stderr: {rc.stderr[:300]}")

    bundle_id = "unknown"
    if rc.returncode == 0:
        try:
            info = json.loads(rc.stdout.replace("\r\n", "\n").replace("\r", "\n"))
            bundle_id = info.get("bundle_id", "unknown")
            log(f"bundle_id={bundle_id}")
        except Exception:
            pass

    # Write result.json
    res = {
        "status": result.get("status", "unknown"),
        "source": source_uri,
        "run_id": run_id,
        "source_id": source_id,
        "providers_used": providers,
        "evidence_summary": result.get("notes", {}),
        "missing": result.get("missing", []),
        "reasons": [m["reason"] for m in result.get("missing", [])],
        "impact": result.get("warnings", []),
        "remote_processing": access == "public_url",
        "cost": 0,
        "latency_ms": elapsed_ms,
        "bundle_id": bundle_id,
        "candidate_path": f"drafts/{source_uri.split('/')[-1] if '/' in source_uri else source_uri}.md",
        "review_status": "pending",
        "captured_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    (scenario_dir / "result.json").write_text(json.dumps(res, indent=2, ensure_ascii=False), encoding="utf-8")

    # Write candidate with valid YAML frontmatter
    title = source_uri.split("/")[-1] if "/" in source_uri else source_uri
    evidence_json = json.dumps(res.get("evidence_summary", {}), indent=2, ensure_ascii=False)
    missing_json = json.dumps(res.get("missing", []), indent=2, ensure_ascii=False)
    status = res.get("status", "partial")

    cand = f"""---
title: "{title}"
type: concept
area: computing
importance: 0.7
confidence: 0.5
created: "{res.get('captured_at', datetime.now(timezone.utc).strftime('%Y-%m-%d'))}"
tags: "oks, e2e, {status}"
status: provisional
source_type: agent-ingest
---

# Candidate: {source_uri}

**Source**: {source_uri}
**Status**: {status}
**Run**: {run_id}
**Bundle**: {bundle_id}
**Providers**: {', '.join(providers)}
**Captured**: {res['captured_at']}

## Evidence Summary

{evidence_json}

## Missing Evidence

{missing_json if missing_json != '[]' else 'None — all required evidence collected.'}

## Review

- [ ] Accept — promote to Wiki
- [ ] Reject — delete draft
- [ ] Edit — modify before promotion

---
*Generated by OKS /ingest skill v0.4.0. Agent may write Candidate. Human must approve Wiki.*
"""
    (scenario_dir / "candidate.md").write_text(cand, encoding="utf-8")

    # Write command log
    (scenario_dir / "command-log.txt").write_text("\n".join(log_lines) + "\n", encoding="utf-8")

    log(f"Audit trail saved to {scenario_dir}")
    return res


def build_markdown(run_id, source_id, source_uri, log):
    repo = Path(r"D:\XiangMuLuoDi\Clone\1263-ux\claude-code-knowledge-studios")
    content = (repo / source_uri).read_bytes()
    man_dir = repo / ".oks" / "runs" / run_id / "manifest"
    art_dir = man_dir / "artifacts"
    art_dir.mkdir(parents=True, exist_ok=True)

    art_path = art_dir / "content.md"
    art_path.write_bytes(content)
    sha = sha256_hex(content)
    fragment_id = f"frag-md-{uuid.uuid4().hex[:8]}"

    se = {"schema_version":"oks-source-envelope/v0.1","source_id":source_id,
          "source_uri":source_uri,"source_modality":"text","access_mode":"local_file",
          "captured_at":datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
          "captured_by":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
          "content_hash":sha,"evidence_manifest_ref":"evidence-manifest.json",
          "policy":{"remote_processing":"deny","sensitivity":"public"}}
    (man_dir / "source-envelope.json").write_text(json.dumps(se, indent=2, ensure_ascii=False), encoding="utf-8")

    primary = {"artifact_id":"content.md","kind":"primary_text","path":"content.md",
               "media_type":"text/markdown","sha256":sha}
    em = {"schema_version":"oks-evidence-manifest/v0.1",
          "manifest_id":f"manifest-{uuid.uuid4().hex[:12]}",
          "source_id":source_id,"status":"complete",
          "fragment_refs":[fragment_id],
          "primary_artifact":primary,"supplementary_artifacts":[],
          "evidence_records":[{ "evidence_id":"ev-md-1","artifact_id":"content.md",
            "kind":"full_text","method":"agent_direct_read",
            "locator":{"kind":"custom","custom_label":"README.md full text"},
            "agent_judgment":"mechanical"}],
          "modalities":{"text":{"modality":"text","status":"succeeded","evidence_count":1}},
          "provenance":{"agent":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
            "tools":[{"name":"text-read","version":None,"cost":None}]},
          "failure_disposition":"none","warnings":[],
          "steps":[{"capability":"document.text.extract","provider":"text-read","status":"succeeded","reason":None}],
          "notes":{"text_chars":len(content)}}
    (man_dir / "evidence-manifest.json").write_text(json.dumps(em, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"status":"complete","notes":{"text_chars":len(content)},"missing":[],"warnings":[]}

def build_scan_pdf(run_id, source_id, source_uri, log):
    repo = Path(r"D:\XiangMuLuoDi\Clone\1263-ux\claude-code-knowledge-studios")
    pdf_path = repo / "tmp" / "pdfs" / "controlled-chinese-scan.pdf"
    content = pdf_path.read_bytes()
    sha = sha256_hex(content)
    man_dir = repo / ".oks" / "runs" / run_id / "manifest"
    art_dir = man_dir / "artifacts"
    art_dir.mkdir(parents=True, exist_ok=True)
    (art_dir / "scan.pdf").write_bytes(content)
    fragment_id = f"frag-spdf-{uuid.uuid4().hex[:8]}"

    se = {"schema_version":"oks-source-envelope/v0.1","source_id":source_id,
          "source_uri":source_uri,"source_modality":"pdf","access_mode":"local_file",
          "captured_at":datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
          "captured_by":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
          "content_hash":sha,"evidence_manifest_ref":"evidence-manifest.json",
          "policy":{"remote_processing":"deny","sensitivity":"public"}}
    (man_dir / "source-envelope.json").write_text(json.dumps(se, indent=2, ensure_ascii=False), encoding="utf-8")

    primary = {"artifact_id":"scan.pdf","kind":"primary_text","path":"scan.pdf",
               "media_type":"application/pdf","sha256":sha}
    evidence = [{"evidence_id":f"ev-scan-p{p}","artifact_id":"scan.pdf",
        "kind":"page_metadata","method":"pdf_lite_text_layer",
        "locator":{"kind":"page","page":p,"total_pages":3},
        "agent_judgment":"mechanical"} for p in range(1,4)]

    em = {"schema_version":"oks-evidence-manifest/v0.1",
          "manifest_id":f"manifest-{uuid.uuid4().hex[:12]}",
          "source_id":source_id,"status":"partial",
          "fragment_refs":[fragment_id],
          "primary_artifact":primary,"supplementary_artifacts":[],
          "evidence_records":evidence,
          "modalities":{"text":{"modality":"text","status":"partial","evidence_count":3}},
          "provenance":{"agent":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
            "tools":[{"name":"pdf-lite","version":"0.0.27","cost":None}]},
          "failure_disposition":"needs_user_action",
          "warnings":["PDF text layer is empty — scanned document. Run: oks capability install watch --yes for RapidOCR support."],
          "steps":[{"capability":"document.text.extract","provider":"pdf-lite","status":"degraded","reason":"text layer empty"}],
          "notes":{"page_count":3,"text_layer":"empty","needs_ocr":True}}
    (man_dir / "evidence-manifest.json").write_text(json.dumps(em, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"status":"partial","notes":{"page_count":3,"text_layer":"empty","needs_ocr":True},"missing":[{"capability":"image.ocr","reason":"RapidOCR not installed"}],"warnings":em["warnings"]}

def build_web(run_id, source_id, source_uri, log):
    repo = Path(r"D:\XiangMuLuoDi\Clone\1263-ux\claude-code-knowledge-studios")
    man_dir = repo / ".oks" / "runs" / run_id / "manifest"
    art_dir = man_dir / "artifacts"
    art_dir.mkdir(parents=True, exist_ok=True)

    req = urllib.request.Request(source_uri, headers={"User-Agent":"oks-e2e/0.4.0"})
    with urllib.request.urlopen(req, timeout=10) as resp:
        html = resp.read()
    sha = sha256_hex(html)
    (art_dir / "page.html").write_bytes(html)
    fragment_id = f"frag-web-{uuid.uuid4().hex[:8]}"

    se = {"schema_version":"oks-source-envelope/v0.1","source_id":source_id,
          "source_uri":source_uri,"source_modality":"web","access_mode":"public_url",
          "captured_at":datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
          "captured_by":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
          "content_hash":sha,"evidence_manifest_ref":"evidence-manifest.json",
          "policy":{"remote_processing":"allow","sensitivity":"public"}}
    (man_dir / "source-envelope.json").write_text(json.dumps(se, indent=2, ensure_ascii=False), encoding="utf-8")

    primary = {"artifact_id":"page.html","kind":"primary_text","path":"page.html",
               "media_type":"text/html","sha256":sha}
    em = {"schema_version":"oks-evidence-manifest/v0.1",
          "manifest_id":f"manifest-{uuid.uuid4().hex[:12]}",
          "source_id":source_id,"status":"complete",
          "fragment_refs":[fragment_id],
          "primary_artifact":primary,"supplementary_artifacts":[],
          "evidence_records":[{ "evidence_id":"ev-web-1","artifact_id":"page.html",
            "kind":"http_response_body","method":"http_fetch",
            "locator":{"kind":"custom","custom_label":f"GET {source_uri} — {len(html)} bytes, HTTP 200"},
            "agent_judgment":"mechanical"}],
          "modalities":{"text":{"modality":"text","status":"succeeded","evidence_count":1}},
          "provenance":{"agent":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
            "tools":[{"name":"http-fetch","version":None,"cost":None}]},
          "failure_disposition":"none","warnings":[],
          "steps":[{"capability":"web.fetch","provider":"http-fetch","status":"succeeded","reason":None}],
          "notes":{"content_bytes":len(html),"http_status":200}}
    (man_dir / "evidence-manifest.json").write_text(json.dumps(em, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"status":"complete","notes":{"content_bytes":len(html),"http_status":200},"missing":[],"warnings":[]}

def build_video(run_id, source_id, source_uri, log):
    repo = Path(r"D:\XiangMuLuoDi\Clone\1263-ux\claude-code-knowledge-studios")
    man_dir = repo / ".oks" / "runs" / run_id / "manifest"
    art_dir = man_dir / "artifacts"
    art_dir.mkdir(parents=True, exist_ok=True)

    meta_result = subprocess.run(["yt-dlp","--dump-json","--no-download",source_uri],
                                capture_output=True, text=True, timeout=30)
    meta_ok = meta_result.returncode == 0 and meta_result.stdout.strip()

    if meta_ok:
        meta = json.loads(meta_result.stdout)
        title = meta.get("title","unknown")
        duration = meta.get("duration","unknown")
    else:
        meta = {}
        title = "unknown"
        duration = "unknown"

    meta_text = json.dumps(meta, ensure_ascii=False)
    sha = sha256_hex(meta_text.encode())
    (art_dir / "metadata.json").write_text(meta_text, encoding="utf-8")
    fragment_id = f"frag-vid-{uuid.uuid4().hex[:8]}"

    se = {"schema_version":"oks-source-envelope/v0.1","source_id":source_id,
          "source_uri":source_uri,"source_modality":"video","access_mode":"public_url",
          "captured_at":datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
          "captured_by":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
          "content_hash":sha,"evidence_manifest_ref":"evidence-manifest.json",
          "policy":{"remote_processing":"allow","sensitivity":"public"}}
    (man_dir / "source-envelope.json").write_text(json.dumps(se, indent=2, ensure_ascii=False), encoding="utf-8")

    primary = {"artifact_id":"metadata.json","kind":"api_response","path":"metadata.json",
               "media_type":"application/json","sha256":sha}

    warnings = []
    if not meta_ok:
        warnings.append("yt-dlp unavailable — no metadata or subtitle extraction possible")
    else:
        warnings.append("Regular subtitles require Bilibili login (cookie auth). Danmaku XML is available without login.")
        warnings.append("Danmaku are user comments, not speech transcription — usable for topic analysis, not speech coverage.")

    em = {"schema_version":"oks-evidence-manifest/v0.1",
          "manifest_id":f"manifest-{uuid.uuid4().hex[:12]}",
          "source_id":source_id,"status":"partial",
          "fragment_refs":[fragment_id],
          "primary_artifact":primary,"supplementary_artifacts":[],
          "evidence_records":[{ "evidence_id":"ev-video-meta","artifact_id":"metadata.json",
            "kind":"platform_metadata","method":"yt_dlp_dump_json",
            "locator":{"kind":"custom","custom_label":f"Bilibili: {title[:80]}"},
            "agent_judgment":"mechanical"}],
          "modalities":{"text":{"modality":"text","status":"partial","evidence_count":1}},
          "provenance":{"agent":{"runtime":"claude-code","model":"claude-opus-5","skill":"/ingest"},
            "tools":[{"name":"yt-dlp","version":"2026.07.04","cost":None}]},
          "failure_disposition":"needs_user_auth",
          "warnings":warnings,
          "steps":[{"capability":"metadata.fetch","provider":"yt-dlp","status":"succeeded","reason":None}],
          "notes":{"title":title[:100],"duration":duration,"subtitle_coverage":"danmaku_only","speech_coverage":"login_required"}}
    (man_dir / "evidence-manifest.json").write_text(json.dumps(em, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"status":"partial","notes":{"title":title[:100],"duration":duration,"subtitle_coverage":"danmaku_only"},"missing":[{"capability":"subtitle.fetch","reason":"Bilibili login required — regular subtitles unavailable"}],"warnings":warnings}


def main():
    audit_base = ensure_dir(_AUDIT / "e2e")
    results = {}

    print("=" * 60)
    print("E2E AUDIT: Markdown")
    results["markdown"] = run_scenario("markdown", "e2e-md", "README.md", "text", "local_file",
                                        ["text-read"], build_markdown)

    print("=" * 60)
    print("E2E AUDIT: Scan PDF")
    results["scan-pdf"] = run_scenario("scan-pdf", "e2e-spdf", "controlled-chinese-scan.pdf", "pdf", "local_file",
                                        ["pdf-lite"], build_scan_pdf)

    print("=" * 60)
    print("E2E AUDIT: Web")
    results["web"] = run_scenario("web", "e2e-web", "https://example.com", "web", "public_url",
                                   ["http-fetch"], build_web)

    print("=" * 60)
    print("E2E AUDIT: Video")
    results["video"] = run_scenario("video", "e2e-vid", "https://www.bilibili.com/video/BV1p4MD6KEaM", "video", "public_url",
                                     ["yt-dlp"], build_video)

    # Summary
    summary = []
    for label, r in results.items():
        summary.append(f"  {label:12s}  run_id={r.get('run_id','?'):30s}  bundle={r.get('bundle_id','?'):30s}  status={r.get('status','?')}")

    summary_text = "# E2E Audit Summary\n\nRun at: " + datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ") + "\nGit commit: " + open(str(_AUDIT / "git-head.txt")).read().strip() + "\n\n" + "\n".join(summary) + "\n"
    (_AUDIT / "e2e-summary.txt").write_text(summary_text, encoding="utf-8")
    print("\n" + summary_text)


if __name__ == "__main__":
    main()
